// web-version/src/components/Game.tsx
import { useState } from 'react';
import { GameProvider, useGame } from '../context/GameContext';
import DialogueSystem from '../components/DialogueSystem';
import WorldMap from '../components/WorldMap';
import LexiconSidebar from '../components/LexiconSidebar';
import MemoryDive from '../components/MemoryDive';
import { prologueChapter, languageSelectionScene, hubScene } from '../data/dialogue';

type GameScreen = 'prologue' | 'language_selection' | 'hub' | 'map' | 'lexicon' | 'memory_dive';

function GameContent() {
  const { state } = useGame();
  const [currentScreen, setCurrentScreen] = useState<GameScreen>('prologue');
  const [currentSceneId, setCurrentSceneId] = useState('prologue_start');

  const handleSceneComplete = () => {
    if (currentScreen === 'prologue') {
      setCurrentScreen('language_selection');
      setCurrentSceneId('language_selection');
    } else if (currentScreen === 'language_selection') {
      setCurrentScreen('hub');
      setCurrentSceneId('hub_main');
    }
  };

  // Removed unused handleHubChoice function since navigation is handled by buttons

  const returnToHub = () => {
    setCurrentScreen('hub');
    setCurrentSceneId('hub_main');
  };

  const renderScreen = () => {
    switch (currentScreen) {
      case 'prologue':
        return (
          <DialogueSystem
            scenes={prologueChapter}
            currentSceneId={currentSceneId}
            onSceneChange={setCurrentSceneId}
            onComplete={handleSceneComplete}
          />
        );
        
      case 'language_selection':
        return (
          <DialogueSystem
            scenes={languageSelectionScene}
            currentSceneId={currentSceneId}
            onSceneChange={setCurrentSceneId}
            onComplete={handleSceneComplete}
          />
        );
        
      case 'hub':
        return (
          <div className="hub-screen">
            <div className="hub-header">
              <h1>Echoes of Ellidra</h1>
              <div className="player-info">
                Welcome, <strong>{state.playerName}</strong>
              </div>
            </div>
            
            <DialogueSystem
              scenes={hubScene}
              currentSceneId={currentSceneId}
              onSceneChange={setCurrentSceneId}
              onComplete={() => {
                // Hub navigation handled by buttons below
              }}
            />
            
            <div className="hub-actions">
              <button onClick={() => setCurrentScreen('map')}>🗺️ Open Map</button>
              <button onClick={() => setCurrentScreen('lexicon')}>📚 Open Lexicon</button>
              <button onClick={() => setCurrentScreen('memory_dive')}>🧠 Memory-Dive</button>
            </div>
          </div>
        );
        
      case 'map':
        return <WorldMap onClose={returnToHub} />;
        
      case 'lexicon':
        return <LexiconSidebar onClose={returnToHub} />;
        
      case 'memory_dive':
        return <MemoryDive onClose={returnToHub} />;
        
      default:
        return <div>Screen not found</div>;
    }
  };

  return (
    <div className="game-container">
      {renderScreen()}
    </div>
  );
}

export default function Game() {
  return (
    <GameProvider>
      <GameContent />
    </GameProvider>
  );
}

// angular-version/src/app/components/game/game.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DialogueSystemComponent } from '../dialogue-system/dialogue-system.component';
import { WorldMapComponent } from '../world-map/world-map.component';
import { LexiconSidebarComponent } from '../lexicon-sidebar/lexicon-sidebar.component';
import { MemoryDiveComponent } from '../memory-dive/memory-dive.component';
import { GameService } from '../../services/game.service';
import { prologueChapter, languageSelectionScene, hubScene } from '../../data/dialogue';

type GameScreen = 'prologue' | 'language_selection' | 'hub' | 'map' | 'lexicon' | 'memory_dive';

@Component({
  selector: 'app-game',
  imports: [
    CommonModule,
    DialogueSystemComponent,
    WorldMapComponent,
    LexiconSidebarComponent,
    MemoryDiveComponent
  ],
  templateUrl: './game.component.html',
  styleUrl: './game.component.css'
})
export class GameComponent implements OnInit {
  currentScreen: GameScreen = 'prologue';
  currentSceneId = 'prologue_start';

  constructor(private gameService: GameService) {}

  ngOnInit() {
    // Initialize game state if needed
  }

  handleSceneComplete() {
    if (this.currentScreen === 'prologue') {
      this.currentScreen = 'language_selection';
      this.currentSceneId = 'language_selection';
    } else if (this.currentScreen === 'language_selection') {
      this.currentScreen = 'hub';
      this.currentSceneId = 'hub_main';
    }
  }

  onSceneChange(sceneId: string) {
    this.currentSceneId = sceneId;
  }

  returnToHub() {
    this.currentScreen = 'hub';
    this.currentSceneId = 'hub_main';
  }

  navigateToScreen(screen: GameScreen) {
    this.currentScreen = screen;
  }

  get prologueChapter() {
    return prologueChapter;
  }

  get languageSelectionScene() {
    return languageSelectionScene;
  }

  get hubScene() {
    return hubScene;
  }
}
<div class="game-container">
  <div [ngSwitch]="currentScreen">
    
    <!-- Prologue Screen -->
    <div *ngSwitchCase="'prologue'">
      <app-dialogue-system
        [scenes]="prologueChapter"
        [currentSceneId]="currentSceneId"
        (sceneChange)="onSceneChange($event)"
        (complete)="handleSceneComplete()"
      ></app-dialogue-system>
    </div>

    <!-- Language Selection Screen -->
    <div *ngSwitchCase="'language_selection'">
      <app-dialogue-system
        [scenes]="languageSelectionScene"
        [currentSceneId]="currentSceneId"
        (sceneChange)="onSceneChange($event)"
        (complete)="handleSceneComplete()"
      ></app-dialogue-system>
    </div>

    <!-- Hub Screen -->
    <div *ngSwitchCase="'hub'">
      <div class="hub-container">
        <app-dialogue-system
          [scenes]="hubScene"
          [currentSceneId]="currentSceneId"
          (sceneChange)="onSceneChange($event)"
          (complete)="handleSceneComplete()"
        ></app-dialogue-system>
        
        <div class="hub-navigation">
          <h3>Explore</h3>
          <div class="nav-buttons">
            <button (click)="navigateToScreen('map')">🗺️ World Map</button>
            <button (click)="navigateToScreen('lexicon')">📖 Lexicon</button>
            <button (click)="navigateToScreen('memory_dive')">🧠 Memory-Dive</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Map Screen -->
    <div *ngSwitchCase="'map'">
      <app-world-map (close)="returnToHub()"></app-world-map>
    </div>

    <!-- Lexicon Screen -->
    <div *ngSwitchCase="'lexicon'">
      <app-lexicon-sidebar (close)="returnToHub()"></app-lexicon-sidebar>
    </div>

    <!-- Memory Dive Screen -->
    <div *ngSwitchCase="'memory_dive'">
      <app-memory-dive (close)="returnToHub()"></app-memory-dive>
    </div>

    <!-- Default/Error Screen -->
    <div *ngSwitchDefault>
      <div class="error-screen">Screen not found: {{currentScreen}}</div>
    </div>

  </div>
</div>
