// web-version/src/components/WorldMap.tsx
import { useState, useEffect } from 'react';
import type { FactionMapData, Region } from '../types/game';
import { useGame } from '../context/GameContext';

interface WorldMapProps {
  onClose: () => void;
}

export default function WorldMap({ onClose }: WorldMapProps) {
  const { state, dispatch } = useGame();
  const [mapData, setMapData] = useState<FactionMapData | null>(null);
  const [selectedRegion, setSelectedRegion] = useState<Region | null>(null);

  useEffect(() => {
    fetch('/data/faction_map.json')
      .then(res => res.json())
      .then(data => setMapData(data))
      .catch(err => console.error('Failed to load map data:', err));
  }, []);

  const handleRegionClick = (region: Region) => {
    setSelectedRegion(region);
    dispatch({ type: 'ADD_CONSEQUENCE', payload: { key: region.id, value: 'inspected' } });
  };

  const closeRegionInfo = () => {
    setSelectedRegion(null);
  };

  if (!mapData) {
    return (
      <div className="map-container">
        <div className="map-loading">Loading map...</div>
        <button onClick={onClose}>Close</button>
      </div>
    );
  }

  return (
    <div className="map-container">
      <div className="map-header">
        <h2>Map of Valdaren</h2>
        <button onClick={onClose} className="close-btn">×</button>
      </div>
      
      <div className="map-content">
        <div className="map-image-container">
          <img 
            src={mapData.map_image} 
            alt="Map of Valdaren"
            className="map-image"
            onError={(e) => {
              const target = e.target as HTMLImageElement;
              target.src = '/assets/placeholder-map.png';
            }}
          />
          
          {mapData.regions.map((region) => (
            <button
              key={region.id}
              className="region-hotspot"
              style={{
                left: `${region.x}px`,
                top: `${region.y}px`,
                width: `${region.w}px`,
                height: `${region.h}px`,
              }}
              onClick={() => handleRegionClick(region)}
              title={region.name}
            />
          ))}
        </div>

        <div className="faction-influence">
          <h3>Faction Influence</h3>
          {Object.entries(state.factionInfluence).map(([faction, influence]) => (
            <div key={faction} className="influence-bar">
              <span className="faction-name">{faction.replace('_', ' ')}</span>
              <div className="bar">
                <div 
                  className="bar-fill" 
                  style={{ width: `${influence}%` }}
                />
              </div>
              <span className="influence-value">{influence}</span>
            </div>
          ))}
        </div>
      </div>

      {selectedRegion && (
        <div className="region-modal">
          <div className="modal-content">
            <h3>{selectedRegion.name}</h3>
            <p><strong>Faction:</strong> {selectedRegion.faction}</p>
            <p><strong>Influence:</strong> {selectedRegion.influence}</p>
            <p>{selectedRegion.description}</p>
            
            <div className="modal-actions">
              <button onClick={closeRegionInfo}>Acknowledge</button>
              <button onClick={() => {
                dispatch({ type: 'ADD_CONSEQUENCE', payload: { key: selectedRegion.id, value: 'investigated' } });
                closeRegionInfo();
              }}>
                Inspect Further
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// angular-version/src/app/components/world-map/world-map.component.ts
import { Component, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FactionMapData, Region } from '../../types/game';
import { GameService } from '../../services/game.service';

@Component({
  selector: 'app-world-map',
  imports: [CommonModule],
  templateUrl: './world-map.component.html',
  styleUrl: './world-map.component.css'
})
export class WorldMapComponent implements OnInit {
  @Output() close = new EventEmitter<void>();
  
  mapData: FactionMapData | null = null;
  selectedRegion: Region | null = null;

  constructor(
    private gameService: GameService,
    private http: HttpClient
  ) {}

  ngOnInit() {
    this.http.get<FactionMapData>('/data/faction_map.json').subscribe({
      next: (data) => this.mapData = data,
      error: (err) => console.error('Failed to load map data:', err)
    });
  }

  handleRegionClick(region: Region) {
    this.selectedRegion = region;
    this.gameService.dispatch({ 
      type: 'ADD_CONSEQUENCE', 
      payload: { key: region.id, value: 'inspected' } 
    });
  }

  closeRegionInfo() {
    this.selectedRegion = null;
  }

  investigateRegion(region: Region) {
    this.gameService.dispatch({ 
      type: 'ADD_CONSEQUENCE', 
      payload: { key: region.id, value: 'investigated' } 
    });
    this.closeRegionInfo();
  }

  onClose() {
    this.close.emit();
  }
}
<div class="map-container">
  <div *ngIf="!mapData" class="map-loading">
    Loading map...
  </div>

  <div *ngIf="mapData">
    <div class="map-header">
      <h2>Map of Valdaren</h2>
      <button (click)="onClose()" class="close-btn">×</button>
    </div>
    
    <div class="map-content">
      <div class="map-image-container">
        <img 
          [src]="mapData.map_image" 
          alt="Map of Valdaren"
          class="map-image"
        />
        
        <div class="regions-overlay">
          <div 
            *ngFor="let region of mapData.regions"
            class="region-marker"
            [style.left.%]="region.x"
            [style.top.%]="region.y"
            [style.width.%]="region.w"
            [style.height.%]="region.h"
            (click)="handleRegionClick(region)"
            [title]="region.name"
          >
            <span class="region-name">{{region.name}}</span>
          </div>
        </div>
      </div>
      
      <div class="factions-list">
        <h3>Factions</h3>
        <ul>
          <li *ngFor="let region of mapData.regions" class="faction-item">
            <strong>{{region.name}}</strong>
            <span class="influence-level">Influence: {{region.influence}}</span>
          </li>
        </ul>
      </div>
    </div>

    <!-- Region Detail Modal -->
    <div *ngIf="selectedRegion" class="modal-overlay" (click)="closeRegionInfo()">
      <div class="modal-content" (click)="$event.stopPropagation()">
        <h3>{{selectedRegion.name}}</h3>
        <p><strong>Faction:</strong> {{selectedRegion.faction}}</p>
        <p><strong>Influence:</strong> {{selectedRegion.influence}}</p>
        <p>{{selectedRegion.description}}</p>
        
        <div class="modal-actions">
          <button (click)="closeRegionInfo()">Acknowledge</button>
          <button (click)="investigateRegion(selectedRegion)">
            Investigate Further
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
