// angular-version/src/app/components/dialogue-system/dialogue-system.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DialogueNode, DialogueChoice } from '../../types/game';
import { GameService } from '../../services/game.service';

@Component({
  selector: 'app-dialogue-system',
  imports: [CommonModule, FormsModule],
  templateUrl: './dialogue-system.component.html',
  styleUrl: './dialogue-system.component.css'
})
export class DialogueSystemComponent implements OnInit, OnChanges {
  @Input() scenes: DialogueNode[] = [];
  @Input() currentSceneId: string = '';
  @Output() sceneChange = new EventEmitter<string>();
  @Output() complete = new EventEmitter<void>();

  currentScene: DialogueNode | null = null;
  showNameInput = false;
  nameInput = '';

  constructor(private gameService: GameService) {}

  ngOnInit() {
    this.updateCurrentScene();
  }

  ngOnChanges() {
    this.updateCurrentScene();
  }

  private updateCurrentScene() {
    this.currentScene = this.scenes.find(scene => scene.id === this.currentSceneId) || null;
    this.showNameInput = this.currentScene?.choices?.some(choice => choice.id === 'choose_name') || false;
    
    // Handle auto-advance
    if (this.currentScene?.autoAdvance) {
      setTimeout(() => {
        this.sceneChange.emit(this.currentScene!.autoAdvance!);
      }, 2000); // Wait 2 seconds before auto-advancing
    }
  }

  handleChoice(choice: DialogueChoice) {
    if (choice.id === 'choose_name') {
      this.showNameInput = true;
      return;
    }

    // Apply consequences
    choice.consequences?.forEach(consequence => {
      this.gameService.dispatch({ type: 'ADD_CONSEQUENCE', payload: { key: 'player_choices', value: consequence } });
    });

    // Unlock memories
    choice.unlocks?.forEach(unlock => {
      this.gameService.dispatch({ type: 'UNLOCK_MEMORY', payload: unlock });
    });

    // Learn languages
    if (choice.id.startsWith('choose_')) {
      const lang = choice.id.replace('choose_', '');
      this.gameService.dispatch({ type: 'LEARN_LANGUAGE', payload: lang });
    }

    // Apply glyph effects
    if (choice.glyphUsed) {
      this.gameService.dispatch({ type: 'ADD_CONSEQUENCE', payload: { 
        key: 'glyphs_used', 
        value: choice.glyphUsed 
      } });
    }

    // Handle navigation
    if (choice.id === 'who_are_you') {
      this.sceneChange.emit('figure_response_identity');
    } else if (choice.id === 'return_from_where') {
      this.sceneChange.emit('figure_response_memory');
    } else if (choice.id === 'use_glyph') {
      this.sceneChange.emit('figure_response_glyph');
    } else if (choice.id.startsWith('choose_') && choice.id !== 'choose_name') {
      this.complete.emit();
    } else {
      // Check for auto-advance
      if (this.currentScene?.autoAdvance) {
        this.sceneChange.emit(this.currentScene.autoAdvance);
      }
    }
  }

  handleNameSubmit() {
    if (this.nameInput.trim()) {
      this.gameService.dispatch({ type: 'SET_PLAYER_NAME', payload: this.nameInput.trim() });
      this.showNameInput = false;
      this.complete.emit();
    }
  }

  onKeyPress(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.handleNameSubmit();
    }
  }

  isChoiceAvailable(choice: DialogueChoice): boolean {
    if (!choice.requiresLanguages) return true;
    
    const state = this.gameService.state;
    return choice.requiresLanguages.every(lang => 
      state.knownLanguages.includes(lang)
    );
  }
}
<div class="dialogue-system" *ngIf="currentScene">
  <div *ngIf="!currentScene" class="dialogue-error">
    Scene not found: {{currentSceneId}}
  </div>

  <div *ngIf="currentScene" class="dialogue-box">
    <div class="speaker-name">{{currentScene.speaker}}</div>
    <div class="dialogue-text">
      {{currentScene.text}}
    </div>
  </div>

  <div *ngIf="showNameInput" class="name-input">
    <input
      type="text"
      [(ngModel)]="nameInput"
      placeholder="Enter your name..."
      maxlength="30"
      (keydown)="onKeyPress($event)"
    />
    <button (click)="handleNameSubmit()" [disabled]="!nameInput.trim()">
      Confirm
    </button>
  </div>

  <div *ngIf="currentScene.choices && !showNameInput" class="dialogue-choices">
    <button
      *ngFor="let choice of currentScene.choices"
      (click)="handleChoice(choice)"
      [class]="'choice-button ' + (isChoiceAvailable(choice) ? 'available' : 'disabled')"
      [disabled]="!isChoiceAvailable(choice)"
    >
      {{choice.text}}
      <span *ngIf="choice.glyphUsed" class="glyph-indicator">✨</span>
      <span *ngIf="choice.requiresLanguages && choice.requiresLanguages.length > 0" class="language-requirement">
        (Requires: {{choice.requiresLanguages.join(', ')}})
      </span>
    </button>
  </div>
</div>

// web-version/src/components/DialogueSystem.tsx
import { useState } from 'react';
import type { DialogueNode, DialogueChoice } from '../types/game';
import { useGame } from '../context/GameContext';

interface DialogueSystemProps {
  scenes: DialogueNode[];
  currentSceneId: string;
  onSceneChange: (sceneId: string) => void;
  onComplete: () => void;
}

export default function DialogueSystem({ 
  scenes, 
  currentSceneId, 
  onSceneChange, 
  onComplete 
}: DialogueSystemProps) {
  const { state, dispatch } = useGame();
  const [showNameInput, setShowNameInput] = useState(false);
  const [nameInput, setNameInput] = useState('');

  const currentScene = scenes.find(scene => scene.id === currentSceneId);

  if (!currentScene) {
    return <div className="dialogue-error">Scene not found: {currentSceneId}</div>;
  }

  const handleChoice = (choice: DialogueChoice) => {
    // Handle name input specially
    if (choice.id === 'choose_name') {
      setShowNameInput(true);
      return;
    }

    // Apply consequences
    choice.consequences?.forEach(consequence => {
      dispatch({ type: 'ADD_CONSEQUENCE', payload: { key: 'choices', value: consequence } });
    });

    // Unlock memories
    choice.unlocks?.forEach(unlock => {
      dispatch({ type: 'UNLOCK_MEMORY', payload: unlock });
    });

    // Learn languages
    if (choice.id.startsWith('choose_')) {
      const lang = choice.id.replace('choose_', '');
      dispatch({ type: 'LEARN_LANGUAGE', payload: lang });
    }

    // Apply glyph effects
    if (choice.glyphUsed) {
      dispatch({ type: 'ADD_CONSEQUENCE', payload: { 
        key: 'glyphs_used', 
        value: choice.glyphUsed 
      } });
    }

    // Handle navigation
    if (choice.id === 'who_are_you') {
      onSceneChange('figure_response_identity');
    } else if (choice.id === 'return_from_where') {
      onSceneChange('figure_response_memory');
    } else if (choice.id === 'use_glyph') {
      onSceneChange('figure_response_glyph');
    } else if (choice.id.startsWith('choose_') && currentSceneId === 'language_selection') {
      onComplete(); // Go to hub after language selection
    } else {
      // Default auto-advance or completion
      if (currentScene.autoAdvance) {
        onSceneChange(currentScene.autoAdvance);
      } else {
        onComplete();
      }
    }
  };

  const handleNameSubmit = () => {
    if (nameInput.trim()) {
      dispatch({ type: 'SET_PLAYER_NAME', payload: nameInput.trim() });
      setShowNameInput(false);
      setNameInput('');
      onComplete(); // Go to language selection
    }
  };

  const canUseChoice = (choice: DialogueChoice) => {
    if (!choice.requiresLanguages) return true;
    return choice.requiresLanguages.every(lang => 
      state.knownLanguages.includes(lang) || state.languageFlags[lang]
    );
  };

  return (
    <div className="dialogue-system">
      <div className="dialogue-box">
        <div className="speaker-name">{currentScene.speaker}</div>
        <div className="dialogue-text">
          {currentScene.text}
        </div>
      </div>

      {showNameInput && (
        <div className="name-input">
          <input
            type="text"
            value={nameInput}
            onChange={(e) => setNameInput(e.target.value)}
            placeholder="Enter your name..."
            maxLength={30}
            onKeyDown={(e) => e.key === 'Enter' && handleNameSubmit()}
          />
          <button onClick={handleNameSubmit} disabled={!nameInput.trim()}>
            Confirm
          </button>
        </div>
      )}

      {currentScene.choices && !showNameInput && (
        <div className="dialogue-choices">
          {currentScene.choices.map(choice => (
            <button
              key={choice.id}
              className={`choice-button ${!canUseChoice(choice) ? 'disabled' : ''}`}
              onClick={() => handleChoice(choice)}
              disabled={!canUseChoice(choice)}
            >
              {choice.text}
              {choice.glyphUsed && (
                <span className="glyph-indicator">✨</span>
              )}
              {choice.requiresLanguages && (
                <span className="requirement">
                  (Requires: {choice.requiresLanguages.join(', ')})
                </span>
              )}
            </button>
          ))}
        </div>
      )}

      {currentScene.autoAdvance && !currentScene.choices && (
        <button 
          className="continue-button"
          onClick={() => onSceneChange(currentScene.autoAdvance!)}
        >
          Continue
        </button>
      )}
    </div>
  );
}
