// web-version/src/components/MemoryDive.tsx
import { useGame } from '../context/GameContext';

interface MemoryDiveProps {
  onClose: () => void;
}

export default function MemoryDive({ onClose }: MemoryDiveProps) {
  const { state, dispatch } = useGame();

  const handleMemoryInteraction = (memoryId: string) => {
    const memory = state.memories[memoryId];
    if (!memory) return;

    if (memory.locked) {
      return; // Show locked message handled in UI
    }

    dispatch({ type: 'ADD_CONSEQUENCE', payload: { key: memoryId, value: 'inspected' } });
  };

  const handleGlyphTranslation = () => {
    if (state.knownLanguages.length > 1) {
      dispatch({ type: 'UNLOCK_MEMORY', payload: 'm_intro' });
      dispatch({ type: 'ADD_CONSEQUENCE', payload: { key: 'translation', value: 'successful' } });
    }
  };

  return (
    <div className="memory-dive">
      <div className="memory-dive-header">
        <h2>Memory-Dive Chamber</h2>
        <button onClick={onClose} className="close-btn">×</button>
      </div>
      
      <div className="chamber-description">
        <p>You activate a Memory-Dive Chamber. The dreamscape shimmers around you. Choose a tether to probe...</p>
      </div>

      <div className="memory-options">
        {Object.values(state.memories).map(memory => (
          <div key={memory.id} className="memory-option">
            <button 
              className={`memory-button ${memory.locked ? 'locked' : 'unlocked'}`}
              onClick={() => handleMemoryInteraction(memory.id)}
            >
              <div className="memory-title">{memory.title}</div>
              <div className="memory-id">({memory.id})</div>
            </button>
            
            {memory.locked ? (
              <div className="memory-status locked">
                <span>🔒</span> The glyph resists — it needs more semantic context to open.
              </div>
            ) : (
              <div className="memory-status unlocked">
                <span>✨</span> {memory.content}
              </div>
            )}
          </div>
        ))}
        
        <div className="translation-option">
          <button 
            className="translation-button"
            onClick={handleGlyphTranslation}
          >
            Attempt to translate a glyph
          </button>
          <div className="translation-info">
            You try to render the glyph through your current languages...
            {state.knownLanguages.length > 1 ? (
              <div className="success-hint">✓ Multiple languages detected - translation may succeed</div>
            ) : (
              <div className="failure-hint">⚠ Not enough interpretative context. Try learning another language.</div>
            )}
          </div>
        </div>
      </div>

      <div className="chamber-footer">
        <button onClick={onClose} className="return-button">Return to Hub</button>
      </div>
    </div>
  );
}

// angular-version/src/app/components/memory-dive/memory-dive.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GameService } from '../../services/game.service';
import { Observable } from 'rxjs';
import { GameState, Memory } from '../../types/game';

@Component({
  selector: 'app-memory-dive',
  imports: [CommonModule],
  templateUrl: './memory-dive.component.html',
  styleUrl: './memory-dive.component.css'
})
export class MemoryDiveComponent {
  @Output() close = new EventEmitter<void>();

  gameState$: Observable<GameState>;
  Object = Object; // Expose Object to template

  constructor(private gameService: GameService) {
    this.gameState$ = this.gameService.state$;
  }

  handleMemoryInteraction(memoryId: string) {
    const state = this.gameService.state;
    const memory = state.memories[memoryId];
    
    if (memory && !memory.locked) {
      this.gameService.dispatch({
        type: 'ADD_CONSEQUENCE',
        payload: { key: 'memory_interactions', value: memoryId }
      });
    }
  }

  handleGlyphTranslation() {
    const state = this.gameService.state;
    
    if (state.knownLanguages.length > 1) {
      // Success case - try to unlock a random locked memory
      const lockedMemories = Object.values(state.memories).filter(m => m.locked);
      if (lockedMemories.length > 0) {
        const randomMemory = lockedMemories[Math.floor(Math.random() * lockedMemories.length)];
        this.gameService.dispatch({
          type: 'UNLOCK_MEMORY',
          payload: randomMemory.id
        });
        
        this.gameService.dispatch({
          type: 'ADD_CONSEQUENCE',
          payload: { key: 'glyph_translations', value: 'success' }
        });
      }
    } else {
      this.gameService.dispatch({
        type: 'ADD_CONSEQUENCE',
        payload: { key: 'glyph_translations', value: 'failed' }
      });
    }
  }

  getMemories(memories: Record<string, Memory>): Memory[] {
    return Object.values(memories);
  }

  onClose() {
    this.close.emit();
  }
}
<div class="memory-dive-container glass-container" *ngIf="gameState$ | async as state">
  <div class="component-header">
    <h2>Memory-Dive Chamber</h2>
    <button (click)="onClose()" class="close-btn">×</button>
  </div>

  <div class="chamber-description">
    <p>You activate a Memory-Dive Chamber. The dreamscape shimmers around you. Choose a tether to probe...</p>
  </div>

  <div class="memory-options">
    <div *ngFor="let memory of getMemories(state.memories); trackBy: trackByMemoryId" class="memory-option">
      <button 
        class="memory-button btn-glass"
        [class.locked]="memory.locked"
        [class.unlocked]="!memory.locked"
        (click)="handleMemoryInteraction(memory.id)"
      >
        <div class="memory-title">{{memory.title}}</div>
        <div class="memory-id">({{memory.id}})</div>
      </button>
      
      <div *ngIf="memory.locked" class="memory-status locked">
        <span>🔒</span> The glyph resists — it needs more semantic context to open.
      </div>
      
      <div *ngIf="!memory.locked" class="memory-status unlocked">
        <span>✨</span> {{memory.content}}
      </div>
    </div>
    
    <div class="translation-option">
      <button 
        class="translation-button btn-primary"
        (click)="handleGlyphTranslation()"
      >
        Attempt to translate a glyph
      </button>
      <div class="translation-info">
        You try to render the glyph through your current languages...
        <div *ngIf="state.knownLanguages.length > 1" class="success-hint">
          ✓ Multiple languages detected - translation may succeed
        </div>
        <div *ngIf="state.knownLanguages.length <= 1" class="failure-hint">
          ⚠ Not enough interpretative context. Try learning another language.
        </div>
      </div>
    </div>
  </div>

  <div class="chamber-footer">
    <button (click)="onClose()" class="return-button btn-glass">Return to Hub</button>
  </div>
</div>
